version: '3'

networks: 
    laravel: 

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports: 
            - "8088:80"
        depends_on: 
            - php
            - mysql
        volumes: 
            - ./src:/var/www/html
            - ./ngnix/app.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - laravel
    
    mysql:
        platform: linux/x86_64
        image: mysql:5.7.34
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "4306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootpass
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9000:9000"
        networks: 
            - laravel